"""Transactional persistence boundaries; no host or database imports."""
from typing import Any, Protocol
from .models import Entity


class Repository(Protocol):
    def get(self, entity_id: str) -> Entity | None: ...
    def add(self, entity: Entity) -> None: ...
    def save(self, entity: Entity, expected_revision: int) -> None: ...
    def list(self, **filters: Any) -> list[Entity]: ...


class UnitOfWork(Protocol):
    def repo(self, kind: str) -> Repository: ...
    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...
    def commit(self) -> None: ...
